site_name: FrostWiki
copyright: Copyright &copy; 2020-2022 FrostDracony
docs_dir: ../docs/en
site_dir: ../site/en

theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
extra:
  alternate:
    - name: English
      link: ../en/
      lang: en

    - name: Deutsch/German
      link: ../de/
      lang: de